# Generated by Django 5.2.4 on 2025-08-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='does_recommend',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
